title: "üí¨ Discuss√£o Geral"
labels: ["discussion"]
body:
  - type: markdown
    attributes:
      value: |
        Use esta discuss√£o para conversas gerais sobre o NŒû√ò Protocol.
        
  - type: textarea
    id: topic
    attributes:
      label: "T√≥pico da Discuss√£o"
      description: "Sobre o que voc√™ quer discutir?"
      placeholder: "Descreva o t√≥pico..."
    validations:
      required: true
      
  - type: textarea
    id: context
    attributes:
      label: "Contexto Adicional"
      description: "Qualquer informa√ß√£o adicional relevante"
      placeholder: "Adicione contexto, links, refer√™ncias..."
      
  - type: checkboxes
    id: tags
    attributes:
      label: "Categorias"
      options:
        - label: "Arquitetura"
        - label: "Protocolo"
        - label: "Desenvolvimento"
        - label: "Comunidade"
        - label: "Outro"

